### ISSUE TITLE
ログイン機能の実装

### ISSUE THREAD

**Issue by ga-tcho** [ikmz0104/pomodoro-clock#13]
- firebase Authを利用
- Twitter認証がしたい

**Comment by ga-tcho** [comment]
## メモ
https://zenn.dev/k_logic24/articles/react-auth-with-firebase

context api 使う
https://zenn.dev/wattanx/articles/1b8d4b7b92a237#context-api-%E3%82%92%E7%94%A8%E3%81%84%E3%81%A6-authprovider-%E3%82%92%E4%BD%9C%E3%82%8B

**Comment by ga-tcho** [comment]
@ikmz0104 
認証ってもうやられてましたっけ？👀

**Comment by ikmz0104** [comment]
@ga-tcho 
やってないm(__)m

**Comment by ga-tcho** [comment]
@ikmz0104 
はーい！お願いしまっす👍🏻

**Comment by ikmz0104** [comment]
Twitter認証がしたい←見落としてた👀

**Comment by ga-tcho** [comment]
@ikmz0104 
やってみたいなぁってだけなんで
なんでも大丈夫です👀

**Comment by ikmz0104** [comment]
・ログイン画面表示しようとした際にエラー
```
Error: could not find react-redux context value; please ensure the component is wrapped in a <Provider>
    at useReduxContext (C:\Users\sekai\pomodoro-clock\node_modules\react-redux\lib\hooks\useReduxContext.js:30:11)
    at useSelector (C:\Users\sekai\pomodoro-clock\node_modules\react-redux\lib\hooks\useSelector.js:133:28)
    at Home (C:\Users\sekai\pomodoro-clock\.next\server\pages\index.js:447:72)
    at processChild (C:\Users\sekai\pomodoro-clock\node_modules\react-dom\cjs\react-dom-server.node.development.js:3353:14)
    at resolve (C:\Users\sekai\pomodoro-clock\node_modules\react-dom\cjs\react-dom-server.node.development.js:3270:5)
    at ReactDOMServerRenderer.render (C:\Users\sekai\pomodoro-clock\node_modules\react-dom\cjs\react-dom-server.node.development.js:3753:22)
    at ReactDOMServerRenderer.read (C:\Users\sekai\pomodoro-clock\node_modules\react-dom\cjs\react-dom-server.node.development.js:3690:29)
    at renderToString (C:\Users\sekai\pomodoro-clock\node_modules\react-dom\cjs\react-dom-server.node.development.js:4298:27)        
    at Object.renderPage (C:\Users\sekai\pomodoro-clock\node_modules\next\dist\next-server\server\render.js:54:854)
    at Function.getInitialProps (C:\Users\sekai\pomodoro-clock\.next\server\vendors-node_modules_next_dist_pages__document_js.js:627:19)
```

**Comment by ikmz0104** [comment]
#### ソリューションリスト
- https://stackoverflow.com/questions/60329421/usedispatch-error-could-not-find-react-redux-context-value-please-ensure-the
- https://qiita.com/r_1105/items/ddcb1ac56df13a0c77ca
- https://github.com/reduxjs/react-redux/issues/1489
- https://www.codegrepper.com/code-examples/javascript/could+not+find+react-redux+context+value%3B+please+ensure+the+component+is+wrapped+in+a+%3CProvider%3E+testing
- http://5.9.10.113/66164315/react-enzyme-test-could-not-find-react-redux-context-value-please-ensure-the-c
- https://www.fixes.pub/program/786985.html

**Comment by ga-tcho** [comment]
react-reduxインストールしてましたっけ👀

**Comment by ikmz0104** [comment]
@ga-tcho 
自分が参考にしてるソースやとreact-reduxインストールして、
Google認証の処理走らせてるのね。。
↓
- https://github.com/GomaGoma676/twitter_firebase/blob/master/src/App.tsx
- https://github.com/GomaGoma676/twitter_firebase/blob/master/src/components/Auth.tsx

**Comment by ga-tcho** [comment]
@ikmz0104 
ふむふむ！なんのエラーですかね…？？TT
reduxあまり使ったことないので…（泣）

エラー嫌い:-(

**Comment by ga-tcho** [comment]
![20210103_194649.jpg](https://user-images.githubusercontent.com/53213591/128714420-30afd590-3fb4-493b-92fb-5a8c9637ea66.jpg)

**Comment by ikmz0104** [comment]
@ga-tcho 

`pages/idnex.tsx`こんな感じで書き換えて、この後
ログインユーザありなしで処理書こうと思ったけどなかなかきちいww

```
import * as React from 'react';
import { useState, useEffect } from 'react';
import dynamic from 'next/dynamic';
import firebase from 'util/firebase';
import CategoryList from 'components/CategoryList';
import Header from 'components/Header';
import Calendar from 'components/Calendar';
import { useSelector, useDispatch } from 'react-redux';
import { selectUser, login, logout } from 'features/userSlice';
import { auth } from '../../lib/db';
import Auth from 'components/Auth';

//ApexCharts読み込むのにNext.jsで必要な設定
const DynamicGraphComponentWithNoSSR = dynamic(() => import('../views/Graph/Graph'), { ssr: false });

const Home: React.FC = (props) => {
  const [categories, setCategories] = useState([]);
  //HomeComponentからredux/userを取得してローカルのuserに渡す
  const user = useSelector(selectUser);
  //login, logoutアクションを送信(dispatch)する
  const dispatch = useDispatch();

  useEffect(() => {
    //firebaseのauth管理下のuser.stateに変化があれば毎回呼び出す
    const unSub = auth.onAuthStateChanged((authUser) => {
      if (authUser) {
        dispatch(
          //useSlice.loginをdispatch
          login({
            uid: authUser.uid,
            photoUrl: authUser.photoURL,
            displayName: authUser.displayName,
          }),
        );
      } else {
        //useSlice.logoutをdispatch
        dispatch(logout());
      }
    });
    return () => {
      unSub();
    };
  }, [dispatch]);

  useEffect(() => {
    async function fetchData() {
      const userId = '12345678'; //テストId
      await Promise.all([getUser(userId), getCategories(userId)]);
    }
    fetchData();
  }, []);

  const getUser = async (userId: any) => {
    try {
      const user = await firebase.getUserData(userId);
    } catch (e) {
      console.error(e);
    }
  };

  const getCategories = async (userId: any) => {
    try {
      const categories = await firebase.getCategories(userId);
      setCategories(categories);
    } catch (e) {
      console.error(e);
    }
  };

  //{user.uid ? (ユーザが存在する時の処理) :(ユーザが存在しない時の処理)}
  return (
    <>
      
      <Header title="みーたんタイマー" />
      <div className="content">
        <div style={{ marginBottom: 40 }}>
          <p className="title">カテゴリー</p>
          <CategoryList categories={categories} />
        </div>
        <div style={{ marginBottom: 40 }}>
          <p className="title">作業時間</p>
          <React.StrictMode>
            <DynamicGraphComponentWithNoSSR />
          </React.StrictMode>
        </div>
        <div style={{ marginBottom: 40 }}>
          <p className="title">カレンダー</p>
          <Calendar />
        </div>
      </div>

      <Auth />
      
    </>
  );
};

export default Home;
```

**Comment by ikmz0104** [comment]
@ga-tcho 
素のてちが見れてめちゃくちゃ嬉しかった放送！！！！！！！！！！！💛

**Comment by ga-tcho** [comment]
@ikmz0104 なんでですかね……

問題なさそうに見えますけどエラー内容が謎ですね🤔(・・?

**Comment by ga-tcho** [comment]
> @ga-tcho 
> 素のてちが見れてめちゃくちゃ嬉しかった放送！！！！！！！！！！！💛

それなです！！！！

**Comment by ikmz0104** [comment]
> @ikmz0104 問題なさそうに見えますけどエラー内容が謎ですね🤔(・・?

[質問](https://github.com/ikmz0104/pomodoro-clock/issues/30#issuecomment-895257236)ふまえて、追撃していこうと思う。
<img width="1442" alt="スクリーンショット 2021-08-09 215716" src="https://user-images.githubusercontent.com/74099733/128723443-e3c8702a-d548-4055-a840-e9805981bd4a.png">

**Comment by ikmz0104** [comment]
## 作業メモ
- redux使ってのGoogle認証が難航（にゃーん状態）
- [redux理解の参考記事](https://docs.github.com/ja/github/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks)

### store, actionの準備　→　redux使う
**store**
```JavaScript
export const store = configureStore({
  reducer: {
    user: userReducer,
  },
});
```

**action**
```JavaScript
interface USER {
  displayName: string;
  photoUrl: string;
}

export const userSlice = createSlice({
  name: 'user',
  initialState:{
    user: {uid:"", photoUrl: "", displayName: ""},
  },
  reducers: {
    login: (state, action) => {
      state.user = action.payload;
    },
    logout: (state) => {
      state.user = {uid:"", photoUrl: "", displayName: ""};
    },
    //USER型のオブジェクトをReactComponentからdispatch(actionを送信)する際に受け取る
    updateUserProfile: (state, action: PayloadAction<USER>)  => {
      //payload/displayNameをRedux/userステート/displayName属性に更新
      state.user.displayName = action.payload.displayName;
      state.user.photoUrl = action.payload.photoUrl;
    },
  },
});

export const { login, logout, updateUserProfile } = userSlice.actions;
```

**redux**
- 必要なモジュールをインポート
- Authコンポーネント（サインイン画面とGoogle認証機能あり）をreduxのProviderコンポーネントでwrap
- Providerのpropsのstoreに作成してあるストアを流す

```JavaScript
import { Provider } from 'react-redux';
import store from 'app/store';

  return (
    <>
      <Provider store={store}>
        <Auth />
      </Provider>
    </>
  );
```

**Comment by ikmz0104** [comment]
@ga-tcho 
所感としてredux使うと面倒かな。できんかったすまーーん。
変に時間かけてもたけど、これでいこう～👀→[ぷっちょメモ](https://github.com/ikmz0104/pomodoro-clock/issues/13#issuecomment-894900471)

**Comment by ga-tcho** [comment]
@ikmz0104 
redux分かんない🥺

**Comment by ikmz0104** [comment]
@ga-tcho 
おなじく(/・ω・)/

**Comment by ikmz0104** [comment]
@ga-tcho 
https://qiita.com/mpyw/items/a816c6380219b1d5a3bf

状態管理をComponentでなく、用意した管理領域`store`で行うことで、
ComponentがUI表示のみに専念できて再利用性が上がる、特に大規模開発においてロジックの整理がしやすいとのこと

**Comment by ga-tcho** [comment]
@ikmz0104 ありがとうございます✨
分かりやすい。ちなみに状態管理はrecoilっていうのもあります！reduxより導入コストは低かった気が👀


ログイン認証で気になった記事φ(..)メモ
https://yoheiko.com/?p=1587
https://tech.mof-mof.co.jp/blog/next-auth-intro/

**Comment by ikmz0104** [comment]
@ga-tcho 
ほんとだ→[「Recoil」とは？ Reduxとの違いを解説](https://ics.media/entry/210224/)
なんかいったりきたりで目が回る～ww
<img width="449" alt="スクリーンショット 2021-08-11 120129" src="https://user-images.githubusercontent.com/74099733/128962985-4dc6032b-97ad-4eac-ae54-8bc496dee379.png">

メモありがとう！！☺

**Comment by ga-tcho** [comment]
![AltruisticAromaticEyelashpitviper-max-1mb.gif](https://user-images.githubusercontent.com/53213591/128963897-6c7625c6-d390-4d39-8c4f-f1b67dc724aa.gif)

@ikmz0104 
目がっ目がっー

**Comment by ikmz0104** [comment]
@ga-tcho 
どこから拾えるねんwww

**Comment by ikmz0104** [comment]
#### 作業メモ
- https://zenn.dev/k_logic24/articles/react-auth-with-firebase
  - `import { User } from 'firebase'`で警告
    - モジュール '"firebase"' にはエクスポートされたメンバー 'User' がありません。'import User from "firebase"' を使用するつもりでしたか?
  - 実行時に`onAuthStateChanged`周りのエラー
    - firebase/authのonAuthStateChangedはユーザがログイン・ログアウトする際に呼び出される
    - user（ステート）にログイン情報があれば`setCurrentUser(user)`、なければRouting走らせてログイン画面に遷移
    - サーバーエラー写真
<img width="1071" alt="スクリーンショット 2021-08-11 141940" src="https://user-images.githubusercontent.com/74099733/128974756-37e5573d-16c1-498b-847e-4377e4af5e50.png">


腹減った

**Comment by ga-tcho** [comment]
> @ga-tcho 
> どこから拾えるねんwww

笑笑
「ミナ Signal gif」で検索🔎

**Comment by ga-tcho** [comment]
@ikmz0104 
夕方触ろうと思ってるので途中でもpushしてもらえれば見てみます👀👀

**Comment by ikmz0104** [comment]
@ga-tcho 
OK!
https://github.com/ikmz0104/pomodoro-clock/tree/13_auth

**Comment by ikmz0104** [comment]
### エラー２の対応
- https://stackoverflow.com/questions/56372981/firebase-onauthstatechanged-error-with-react

**Comment by ikmz0104** [comment]
@ga-tcho 
https://github.com/ikmz0104/pomodoro-clock/commit/9c2d6bfb1855f7e6bf5f635acb4193b015943717
まじか～👀
ありがとう！！

細かい修正しときまーす

**Comment by ga-tcho** [comment]
@ikmz0104 もうちょっと触っていいですか？👀

**Comment by ikmz0104** [comment]
@ga-tcho 
https://github.com/ikmz0104/pomodoro-clock/commit/36d6d2ddb30c755408512e9ddc8172fb0e5f66c9

ログイン後にFirebaseのKey項目が表示されるエラーがでるけど、
その該当コード消すとログアウト処理が走らなくなるからいったんは元のログアウト処理が走るほうに戻しとく。

> @ikmz0104 もうちょっと触っていいですか？👀

ＯＫ
これからいじらないようにしとく。

**Comment by ga-tcho** [comment]
もう触りません！

**Comment by ikmz0104** [comment]
@ga-tcho 
すげえええ
ありがとう！☺

最新の[push](https://github.com/ikmz0104/pomodoro-clock/commit/101e82efecb072e2b1d931d101cde47ce2471752)でさ、ぷっちょの環境やと問題ないと思うけど、
自分の環境でデバッグしたらちょっとエラーでるのでメモしておく(ﾟДﾟ)ﾉ

```
SerializableError: Error serializing `.currentUser` returned from `getServerSideProps` in "/".
Reason: `undefined` cannot be serialized as JSON. Please use `null` or omit this value.
```

**Comment by ikmz0104** [comment]
@ga-tcho 
↑
エラー解決したのでOK。
このチケットクローズしてもOK??

**Comment by ikmz0104** [comment]
ログイン・ログアウト・サインアップ機能実装済みのため本チケットクローズしまーす🐈

**Comment by ga-tcho** [comment]
@ikmz0104 おけです![20210623_140517.jpg](https://user-images.githubusercontent.com/53213591/129126847-96070cd5-f26d-41d4-890c-99bd0aa1c0f3.jpg)

**Comment by ikmz0104** [comment]
@ga-tcho 
![maaji](https://user-images.githubusercontent.com/74099733/129128379-2111672d-d90a-4d5a-a9ed-037ded3ec9dc.jpg)

済みです
