### ISSUE TITLE
ブランチ命名規則は必要か否か

### ISSUE THREAD

**Issue by ikmz0104** [ikmz0104/pomodoro-clock#16]
追加機能が増える見込みなので、ブランチ命名規則を設けたほうが良いかも・・・

・[ブランチ命名規則](https://qiita.com/c6tower/items/fe2aa4ecb78bef69928f)
・[ブランチ名の変更](https://qiita.com/suin/items/96c110b218d919168d64)

**Comment by ga-tcho** [comment]
確かにそうですね

**Comment by ikmz0104** [comment]
TwitterのDMにて、
「#IssuesID_Featurename」と命名することに決定した。
例えば「ログイン機能の実装」は「#13_login」

**Comment by ikmz0104** [comment]
クローズしちゃいます！
