### ISSUE TITLE
カテゴリ削除モーダルの追加

### ISSUE THREAD

**Issue by ikmz0104** [ikmz0104/pomodoro-clock#24]

**Comment by ikmz0104** [comment]
UIだけ少し修正した。
削除モーダルは途中で終わったのでまた今度やります。

**Comment by ikmz0104** [comment]
いったんマージ。モーダル後で

**Comment by ga-tcho** [comment]
@ikmz0104 
ありがとうございます✨

**Comment by ikmz0104** [comment]
@ga-tcho 
にゃーん🐈

8月は時間取れそうなので、みーたんタイマーメインでやっていきます(/・ω・)/
調べて分からないことあったら聞きます！

**Comment by ikmz0104** [comment]
いらんか

**Comment by ga-tcho** [comment]
@ikmz0104 ありがとうございます☺️
