### ISSUE TITLE
ApexChartsの実装(複数カテゴリ)

### ISSUE THREAD

**Issue by ikmz0104** [ikmz0104/pomodoro-clock#26]
### CloudFireStoreから連携する仕様に変更
- [x] ログインユーザのタスクのみレンダリング→表示
- [x] グラフ要素に組み込む
- [x] 複数カテゴリグラフ

**Comment by ikmz0104** [comment]
現在ログインしているユーザのタスクの時間（Firebaseに登録された）をレンダリングして表示できた。
次はグラフの要素にその要素を追加していく。

**Comment by ikmz0104** [comment]
いったんcloudfirestoreから取得したデータをjavascriptでグラフ描画する（テスト）

**Comment by ikmz0104** [comment]
@ga-tcho 
ApexChartsの下記コードの実装で、
cloudfirestoreから取得した値 (name, time) をそれぞれ (name, data) に格納したいんやけど、ちょっとうまくいかない状況👀
今日時間あったら手貸してほしい(m´・ω・｀)m
```JavaScript
class Graph extends Component<{}, { series: any[]; options: any }> {
  constructor(props) {
    super(props);

    this.state = {
      series: [
        {
          name: 'React', // ←categories/doc/name
          data: [31, 40, 28, 51, 42, 109, 100], // ←categories/doc/time
        },
        {
          name: 'みーたん', // ←categories/doc/name
          data: [11, 32, 45, 32, 34, 52, 41], // ←categories/doc/time
        },
      ],
```

**Comment by ga-tcho** [comment]
@ikmz0104 おけです。🙌🏻時間あるときに見ときます

**Comment by ga-tcho** [comment]
@ikmz0104 ブランチがわからなかったのでdevelopmentに直接pushしました汗汗

**Comment by ikmz0104** [comment]
@ga-tcho 
おおすまぬ🙏
確認します、ありがとうございます😊

**Comment by ikmz0104** [comment]
## TSエラーメモ（帰宅後に対処）
https://github.com/ikmz0104/pomodoro-clock/blob/ac7157be2276f4add6eb5987c884e33977fd7e33/src/views/ApexCharts/index.tsx#L53

optionsに対して
```
この呼び出しに一致するオーバーロードはありません。
  2 中 1 のオーバーロード, '(props: Props | Readonly<Props>): ReactApexChart' により、次のエラーが発生しました。
    型 '{ chart: { height: number; type: string; }; dataLabels: { enabled: boolean; }; stroke: { curve: string; }; xaxis: { type: string; labels: { datetimeFormatter: { year: string; month: string; day: string; hour: string; }; }; }; tooltip: { ...; }; }' を型 'ApexOptions' に割り当てることはできません。
      'chart.type' の型は、これらの型同士で互換性がありません。
        型 'string' を型 '"area" | "line" | "bar" | "histogram" | "pie" | "donut" | "radialBar" | "scatter" | "bubble" | "heatmap" | "treemap" | "boxPlot" | "candlestick" | "radar" | "polarArea" | "rangeBar"' に割り当てることはできません。
  2 中 2 のオーバーロード, '(props: Props, context: any): ReactApexChart' により、次のエラーが発生しました。
```

**Comment by ikmz0104** [comment]
## グラフ化メモ
- data[]が空
- データ取れてない
  - もち手動で打ったらプロット可
<img width="856" alt="スクリーンショット 2021-08-25 081510" src="https://user-images.githubusercontent.com/74099733/130703346-b98a5b14-c675-41f6-94a1-08106f04bfcd.png">

**Comment by ikmz0104** [comment]
2つ目のdata[]入るように修正。お風呂入る🛀
<img width="362" alt="スクリーンショット 2021-08-29 104729" src="https://user-images.githubusercontent.com/74099733/131242849-efaf1ebd-bdab-4da6-b38c-d12e36cd5811.png">

**Comment by ga-tcho** [comment]
🛀

**Comment by ikmz0104** [comment]
categoryId二つともちゃんとれてた。
FireStoreに登録してたcategoryIdの先頭にスペース入っててデータフェッチできてなかったwwwww

<img width="1018" alt="スクリーンショット 2021-08-30 202237" src="https://user-images.githubusercontent.com/74099733/131332005-173de6dc-90f6-45e8-8c16-2d655cfee1b9.png">

**Comment by ikmz0104** [comment]
マージ　is　done

**Comment by ga-tcho** [comment]
ありがとうございます(づ｡◕‿‿◕｡)づ
