### ISSUE TITLE
その他

### ISSUE THREAD

**Issue by ga-tcho** [ikmz0104/pomodoro-clock#27]

**Comment by ga-tcho** [comment]
@ikmz0104 
[tailwindcss](https://tailwindcss.com/docs)とか気になるライブラリとかあれば適当に入れてもいいですか？

**Comment by ikmz0104** [comment]
@ga-tcho 
もちろんです！☺

**Comment by ikmz0104** [comment]
OK
またの機会に
おやすみーたん！
