### ISSUE TITLE
ソースコード質問

### ISSUE THREAD

**Issue by ikmz0104** [ikmz0104/pomodoro-clock#30]
Reactを理解したい

**Comment by ikmz0104** [comment]
大まかに理解があってるか見てほしい～

- userIdはタイマー使用時に一時的に割り当てたもの
- `Promise.all([getUser(userId), getCategories(userId)]);`でfirebaseのcategories/userIdを全部取得する??

pages/index.tsx

```
  useEffect(() => {
    async function fetchData() {
      const userId = '12345678'; //テストId
      await Promise.all([getUser(userId), getCategories(userId)]);
    }
    fetchData();
  }, []);

```

**Comment by ga-tcho** [comment]
しばしお待ちを！>.<
今日で三連休終わりですね:-(

**Comment by ga-tcho** [comment]
>userIdはタイマー使用時に一時的に割り当てたもの

そうです！firebase.jsの`getUserId()`見てもらったら分かります！`12345678`が値として返るようになってます.


>Promise.all([getUser(userId), getCategories(userId)]);でfirebaseのcategories/userIdを全部取得する??

getUser(userId), getCategories(userId)ですが、

index.tsの中にこのコードあると思います
```index.ts
  const getUser = async (userId: any) => {
    try {
      const user = await firebase.getUserData(userId);//これと
    } catch (e) {
      console.error(e);
    }
  };

  const getCategories = async (userId: any) => {
    try {
      const categories = await firebase.getCategories(userId);//これ
      setCategories(categories);
    } catch (e) {
      console.error(e);
    }
  };
```

データ取得はfirebase.jsの中に書いてあります
```firebase.js
  getUserData = async (userId) => {
    let userData = {};
    const ref = this.users.doc(userId);
    try {
      await ref.get().then((doc) => {
        if (doc.exists) {
          userData.uid = doc.id;
          userData = doc.data();
        }
      });
      return userData;
    } catch (e) {
      throw e;
    }
  };

  getCategories = async (userId) => {
    let data = [];
    const ref = this.categories.where('userId', '==', userId); //←WHERE
    try {
      await ref.get().then(function (querySnapshot) {
        querySnapshot.forEach(function (doc) {
          data.push({ ...doc.data(), id: doc.id });
        });
      });
      return data;
    } catch (e) {
      throw e;
    }
  };
```

getUserは`users/userId`のドキュメントを取得,
getCategoriesは`categories/`の中の、`引数で渡したuserId` === `documentのuserId`である全てのカテゴリーを取得してます！
(SQLっぽく言うと, カテゴリーテーブルでカラムのuserIdが12345678である全てのレコードを取得している)

**Comment by ga-tcho** [comment]
@ikmz0104 
> 実は有給とってるので、来週日曜日まで休みますww
そうなんですね！！9連休！！！😆

**Comment by ikmz0104** [comment]
いとありがたし！☺

> getUserはusers/userIdのドキュメントを取得,

これか👀

<img width="1418" alt="スクリーンショット 2021-08-09 231512" src="https://user-images.githubusercontent.com/74099733/128721022-a858d09e-aa5c-436f-a90d-fae11166bd94.png">

てか、その辺質問しようとしてたからびっくり～

<img width="750" alt="スクリーンショット 2021-08-09 231335" src="https://user-images.githubusercontent.com/74099733/128721184-c57e1f4c-3b8e-40ce-ab3c-a8b261e01ea5.png">

**Comment by ikmz0104** [comment]
@ga-tcho 
SQLの説明わかりやすい、ありがとう☺

**Comment by ga-tcho** [comment]
@ikmz0104 そうですね。なので今は`getUserData`関数はuserIdとnameが格納された連想配列が返ってくると思います。
取得してるけど使ってない...()

**Comment by ikmz0104** [comment]
@ga-tcho 
> @ikmz0104 そうですね。なので今はgetUserData関数はuserIdとnameが格納された連想配列が返ってくると思います。
でも取得してるけど使ってない...()

ちょっと困惑してたwww
ありがとう！理解はできたと思う☺

**Comment by ikmz0104** [comment]
@ga-tcho 
react-redux使ってuserを作ってたから、user関係で何かかぶったのかと思った。
見よう見まねでreact-redux使ってる危ない人です👀

**Comment by ga-tcho** [comment]
@ikmz0104 
> ちょっと困惑してたwww
> ありがとう！理解はできたと思う☺

汚いコードですみませんw

**Comment by ga-tcho** [comment]
@ikmz0104 
大規模開発だとredux必須ですが, redux使うとコードの可読性下がるし覚えることも増えるので、できるだけ使わずに実装してますw

**Comment by ikmz0104** [comment]
クローズしまーす！
