### ISSUE TITLE
ログインフォームのUI更新

### ISSUE THREAD

**Issue by ikmz0104** [ikmz0104/pomodoro-clock#32]
ログイン画面をもう少しきれいにしたい

- [x] みーたんの画像を用意
- [x] Material Iconsで適宜UI調整
- [x] ログイン画面のUI修正（なぜか左半分に偏る）
- [x] SimpleBottomNavigation コンポーネントの非表示

### 参考
https://github.com/mui-org/material-ui/tree/master/docs/src/pages/getting-started/templates/sign-in-side
```
npm i @material-ui/core
npm i @material-ui/icons
```

**Comment by ikmz0104** [comment]
- ログインフォーム、ログアウトボタンのUIを修正済み
  - いきなりサーバーエラーが再発したのでpushできないため、いったんログイン画面用のみーたんの画像を集める

**Comment by ikmz0104** [comment]
@ga-tcho 
ワクチンお疲れ様☺
確認なんやけど、cookie使ってSSRしたコミット以降（https://github.com/ikmz0104/pomodoro-clock/commit/1c79a524e1c9703de497338f37fbc4c73a723a1f ）、
ビルド時に下記のサーバーエラーとかでてこない？👀

```
Error: Error serializing `.currentUser` returned from `getServerSideProps` in "/".
Reason: `undefined` cannot be serialized as JSON. Please use `null` or omit this value.
```

**Comment by ga-tcho** [comment]
undefined使っちゃだめのかな？👀
すみませんそれは知りませんでした。nullか空文字にして対応すればいいのか？👀
今ワクチン打ったとこで15分待たされてるので確認できないです（泣）

**Comment by ga-tcho** [comment]
https://github.com/ikmz0104/pomodoro-clock/blob/d8928414df40c4de454c8b568749de6961ef76b3/src/auth/AuthProvider.tsx#L17

ここの3つ目の引数にundefined入れてるのがまずいんですかね？nullか空文字にすべき？

**Comment by ikmz0104** [comment]
@ga-tcho 
タイムリーワクチン！👀
安静にしてくれ！！！

**Comment by ga-tcho** [comment]
そしてここもundefinedで場合分けじゃなくてnullか空文字に合わせる
https://github.com/ikmz0104/pomodoro-clock/blob/d8928414df40c4de454c8b568749de6961ef76b3/src/pages/index.tsx#L22

**Comment by ikmz0104** [comment]
@ga-tcho 
ありがとう🙆‍♂️
🤏ちょっと試すね！

**Comment by ga-tcho** [comment]
@ikmz0104 今のところなんの副作用も出てないんで今のうちにw

**Comment by ikmz0104** [comment]
@ga-tcho 
ぷっちょありがとう～
解決したのでpushした　→　https://github.com/ikmz0104/pomodoro-clock/commit/8aaa6c77fec6cbc2306006f1e699c9a80f84800c

安静にね～👀

**Comment by ga-tcho** [comment]
@ikmz0104 
お、良かったです！

**Comment by ikmz0104** [comment]
<img width="1912" alt="スクリーンショット 2021-08-12 200703" src="https://user-images.githubusercontent.com/74099733/129186891-0ecb1420-4414-4f20-aef5-95385f959063.png">

**Comment by ga-tcho** [comment]
@ikmz0104 おおおおお！！！！

**Comment by ga-tcho** [comment]
最高すぎますすぎます！✨

**Comment by ga-tcho** [comment]
@ikmz0104 
おけです！_app.tsxに今buttomコンポーネント入ってるます。確か。

**Comment by ikmz0104** [comment]
``` JavaScript
const App: React.FC<AppProps> = ({ Component, pageProps }) => {
  return (
    <ThemeProvider theme={muiTheme}>
      <AuthProvider>
        <Component {...pageProps} />
        <SimpleBottomNavigation /> //←こいつww
      </AuthProvider>
    </ThemeProvider>
  );
};
````

**Comment by ikmz0104** [comment]
`views/Navigation`

```JavaScript
export default function SimpleBottomNavigation() {
  const [value, setValue] = React.useState('');
  const router = useRouter();

  const handleChange = (event, newValue) => {
    router.push(`${newValue}`);
    setValue(newValue);
  };

//このへんか
  return (
    <BottomNavigation value={value} onChange={handleChange} showLabels className={styles.root}>
      {Navigations.map((item) => (
        <BottomNavigationAction label={item.label} value={item.value} icon={item.icon} key={item.value} />
      ))}
    </BottomNavigation>
  );
}
```

**Comment by ikmz0104** [comment]
条件分岐するほどのことではないので各ページに下記の内容を追記して完了。
``` JavaScript
import SimpleBottomNavigation from 'views/Navigation';

<SimpleBottomNavigation />
```

**Comment by ikmz0104** [comment]
レスポンシブ対応ではないけどそこは後w
CSSわかんない

**Comment by ikmz0104** [comment]
無事マージ済みのためクローズします。
