### ISSUE TITLE
パスワードリセット（メール送信ロジック）

### ISSUE THREAD

**Issue by ikmz0104** [ikmz0104/pomodoro-clock#40]
- [x] メール送信ロジック
- [x] 送信ボタンの配置（CSS）

**Comment by ikmz0104** [comment]
できた！
https://github.com/ikmz0104/pomodoro-clock/commit/6fd7b1bf2e3d8e11ba38130394ff3bb81e859421

**Comment by ga-tcho** [comment]
@ikmz0104 
すみませんめっちゃコンフリしてるかもdeath...

**Comment by ikmz0104** [comment]
無事マージ済みのためクローズします🐧
