### ISSUE TITLE
エビングハウスの忘却曲線の実装

### ISSUE THREAD

**Issue by ikmz0104** [ikmz0104/pomodoro-clock#43]
タスクリスト（カテゴリー）のうち暗記物（復習が必要なタスク）に対して、
忘却率が50%（暫定）よりも下回れば警告をしてくれるリマインダーを設定したい。

- [x] エビングハウスコンポーネントを追加
- [x] DB連携

**Comment by ikmz0104** [comment]
検証で適当に値打って表示されるので、クラス→関数への書き換えはOK
DB連携途中。24時間少ないぞ

**Comment by ikmz0104** [comment]
_φ(･_･
Firestoreのデータ構造変える。
1つ目のデータだけプロット。

**Comment by ikmz0104** [comment]
@ga-tcho 
すごい簡単な質問なんやけど、
props/memory/dataに格納したFirestoreのデータ(↓)をmemory[]配下に置けなくて詰まってる
`0:{memory: 100, name: "0 min"}
1:{memory: 58, name: "20 min"}`

時間あるときにコード見てほしい！m(__)m
- https://github.com/ikmz0104/pomodoro-clock/blob/43_memory/src/pages/index.tsx
- https://github.com/ikmz0104/pomodoro-clock/blob/43_memory/src/util/firebase.js
- https://github.com/ikmz0104/pomodoro-clock/blob/43_memory/src/views/Ebbinghaus/index.tsx

**Comment by ikmz0104** [comment]
## 今の状況

<img width="398" alt="スクリーンショット 2021-09-04 103822" src="https://user-images.githubusercontent.com/74099733/132078485-627bfa4e-1b30-4e38-8158-045282757751.png">
<img width="707" alt="スクリーンショット 2021-09-04 104015" src="https://user-images.githubusercontent.com/74099733/132078513-9ca1838b-418d-4e51-8273-9069920db16c.png">


## こうしたい（memoryデータ2, 3は手打ち👀）

<img width="455" alt="スクリーンショット 2021-09-04 103911" src="https://user-images.githubusercontent.com/74099733/132078519-49383046-e98e-4a96-a05b-85ec15308a7d.png">
<img width="830" alt="スクリーンショット 2021-09-04 103928" src="https://user-images.githubusercontent.com/74099733/132078521-c1a6ec7f-1fa3-4199-ac72-3f1db3c0c59b.png">

**Comment by ga-tcho** [comment]
@ikmz0104 
なるほど！ご飯食べてから見てみまっす

**Comment by ga-tcho** [comment]
@ikmz0104 
これってカテゴリーごとの忘却曲線出せるようにする感じですっけ？>0<

**Comment by ga-tcho** [comment]
## 変更したデータ取得
```js
memories :[
    {memory: [{name: '', memory: 100}, {name: '', memory: 50}...]}  //カテゴリーidごとのメモリー
    {memory: [...]} 
    ...
]
```

**Comment by ikmz0104** [comment]
@ga-tcho 

> これってカテゴリーごとの忘却曲線出せるようにする感じですっけ？>0<

できればそうしたい！( *´艸｀)

**Comment by ga-tcho** [comment]
@ikmz0104 一応修正してpushしました！
みずねこさんのほうでもちゃんとデータ取得できてますかね？👀

**Comment by ikmz0104** [comment]
@ga-tcho 
ありがとう☺
きた！
<img width="733" alt="スクリーンショット 2021-09-04 152125" src="https://user-images.githubusercontent.com/74099733/132085039-871d4088-dbab-4665-afd9-75bab8adfb28.png">

**Comment by ikmz0104** [comment]
firebase.jsのmemory→memoriesに変更したらいけた👀
https://github.com/ikmz0104/pomodoro-clock/blob/c70820b27ca5db1576ba83f470d9e021fd9dd921/src/util/firebase.js#L169

**Comment by ikmz0104** [comment]
( ..)φメモメモ
初期値からこれいけるか👀
```
    const data: any = [
      {
        "name": "0",
        "memory": 100,
      },
      {
        "name": "20min",
        "memory": 58,
      },
      {
        "name": "1h",
        "memory": 44,
      },
      {
        "name": "9h",
        "memory": 35,
      },
      {
        "name": "24h",
        "memory": 34,
      },
      {
        "name": "2days",
        "memory": 27,
      },
      {
        "name": "6days",
        "memory": 25,
      },
      {
        "name": "31days",
        "memory": 21,
      },
    ]
```

**Comment by ikmz0104** [comment]
DB連携終わったのでいったんクローズ
追加機能は別チケットにて👀
