### ISSUE TITLE
ちょっとUI修正

### ISSUE THREAD

**Issue by ikmz0104** [ikmz0104/pomodoro-clock#57]
眠いのでUIだけ修正してみる(˘ω˘)

**Comment by ikmz0104** [comment]
UIっていうか、ページ2つ追加しちゃった。
いらないなあ～と思い始めたら消そうw

**Comment by ikmz0104** [comment]
ずっと聴いてた♪
https://www.youtube.com/watch?v=qzKu3QMw0ig

**Comment by ikmz0104** [comment]
最高だす( *´艸｀)

**Comment by ga-tcho** [comment]
1時間！すごい

**Comment by ga-tcho** [comment]
ikuraさん同い年なので、すごいなぁ…といつも思います

**Comment by ikmz0104** [comment]
リリース後にまた！
