### ISSUE TITLE
ヒートカレンダーの実装

### ISSUE THREAD

**Issue by ikmz0104** [ikmz0104/pomodoro-clock#9]
- [x] ヒートカレンダーコンポーネントを追加
- [x] DB連携

１．react-heat-calender
GitHubのcontributionと同じUI、タイマー経過分に比例して色を濃くしたい
https://www.npmjs.com/package/react-calendar-heatmap

２．color-calender
無難なカレンダーUI
https://www.npmjs.com/package/color-calendar#usage-react

**Comment by ikmz0104** [comment]
デモ用レポ
https://github.com/ikmz0104/react-calendar-heatmap

**Comment by ikmz0104** [comment]
参考
https://www.npmjs.com/package/react-heat-calendar

**Comment by ikmz0104** [comment]
変な警告が出たけれどコンパイルは通った
```
PS C:\Users\sekai\pomodoro-clock> npm install react-heat-calendar
npm WARN deprecated core-js@1.2.7: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.   
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

+ react-heat-calendar@1.1.3
added 13 packages from 131 contributors and audited 402 packages in 5.906s

53 packages are looking for funding
  run `npm fund` for details

found 2 low severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details

```

**Comment by ikmz0104** [comment]
`index.js`にべた書きの状態なので、初期設定としては未完成。

**Comment by ikmz0104** [comment]
ブランチ名変更してマージしたらちょっとおかしくなったかも
ローカルでプルしてもリモートブランチの名前変更されないのはなぜ

**Comment by ikmz0104** [comment]
( ,,`･ω･´)ﾝﾝﾝ？うまくいってる

**Comment by ga-tcho** [comment]
@ikmz0104 
おおお？
後で見てみます🤤

**Comment by ikmz0104** [comment]
src/pages/index.tsxにタイマーを使用した日付をべた書きした状態はまずい(´；ω；`)ｳｯ…
別ファイルに書いてimportとかかな

**Comment by ikmz0104** [comment]
最終的には、タイマーの経過時間をDBにセットしてそれを取得したいけどできるのか( ,,`･ω･´)ﾝﾝﾝ？
FireStore Databaseちゃんと理解しよう

**Comment by ikmz0104** [comment]
これ読む
https://techblog.kayac.com/rtdb-vs-firestore

**Comment by ga-tcho** [comment]
記録のdbの形も今のでいいのか。🤔
HeatCalendarに合わせて最適な形にしないとですね

**Comment by ikmz0104** [comment]
みーたんは崩したくない！w

**Comment by ga-tcho** [comment]
@ikmz0104 
隠し機能みたいなの作って、見つけた人だけみーたん見れるみたいなのあれば
...w

**Comment by ikmz0104** [comment]
@ga-tcho 
課金ですねw

**Comment by ikmz0104** [comment]
- document Id はランダム文字列を自動生成
- タイマーで時間（例；25分）を記録するときに, dateとcategoryIdで検索
- 検索に対応するdocument Idが既が存在すれば、timeを上書き（time = time + 25）
- 対応しなければ、新しくdocument Idを作成してdateとcategoryIdとtimeを格納

**Comment by ikmz0104** [comment]
### DB連携
まずはdateとsomeAttrの扱い方をざっと書いた
明日の夜に、少し進めてコミットしたい👀

**Comment by ikmz0104** [comment]
連携できた。
Firestoreに登録した日付が反映されとる👀

<img width="533" alt="スクリーンショット 2021-09-08 211521" src="https://user-images.githubusercontent.com/74099733/132507730-5fbb955c-8a7e-4a14-b2c8-82d9664812cc.png">

**Comment by ikmz0104** [comment]
フィールドに登録した日付が連携できた、OK
<img width="607" alt="スクリーンショット 2021-09-08 221837" src="https://user-images.githubusercontent.com/74099733/132518592-d9c27793-93bc-4fa5-8115-6d95eb17d77e.png">

**Comment by ikmz0104** [comment]
マージ　is　Done
いったんクローズ、他機能は別チケットにて～
